apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  ports:
  - name: pma
    port: 5000
    targetPort: 5000
  selector:
    app: phpmyadmin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
spec:
  template:
    metadata:
      name: phpmyadmin-pod
      labels:
        app: phpmyadmin
        type: pmatype
    spec:
      containers: 
        - name: phpmyadmin
          image: phpmyadmin_image
          imagePullPolicy: Never
          ports:
            - name: phpmyadmin
              containerPort: 5000
          livenessProbe:
            exec:
              command:
                - sh
                - /probe.sh
            initialDelaySeconds: 20
            periodSeconds: 10
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
      type: pmatype
