apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  type: LoadBalancer
  ports:
  - name: port21
    port: 21
    targetPort: 21
  - name: port21000
    port: 21000
    targetPort: 21000
  selector:
    app: ftps
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      name: ftps-pod
      labels:
        app: ftps
    spec:
      containers: 
        - name: ftps
          image: ftps_image
          imagePullPolicy: Never
          ports:
            - name: port21
              containerPort: 21
            - name: port21000
              containerPort: 21000
          livenessProbe:
            tcpSocket:
              port: 21
            initialDelaySeconds: 20
            periodSeconds: 10
